name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test.yml'
      - 'package.json'
      - 'yarn.lock'
      - 'tsconfig.json'
      - 'src/*'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test.yml'
      - 'package.json'
      - 'yarn.lock'
      - 'tsconfig.json'
      - 'src/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'yarn'

    - name: Install
      run: yarn install

    - name: Test
      run: yarn test

    - name: Build
      run: yarn build

    - name: Install test
      run: |
        npm init -y
        npm install ..
        ./node_modules/.bin/generate-icons -m ../test-data/manifest.json ../test-data/test.svg
        test -f ../test-data/test.ico
        test -f ../test-data/test.png
      working-directory: ./check

